### PR TITLE
fix: remove caller, txn_hash from setController

### PR DESCRIPTION
**Pull request by dtbuchholz**
- Values of `caller` and `txn_hash` are not part of the `setController` call
- Closes issue [205](https://github.com/tablelandnetwork/go-tableland/issues/205)

### CODE REVIEW

**Comment by dtbuchholz** [comment]
I haven't opened any PRs here or worked through GitHub best practices with our org, so lmk if any of what I'm doing here is out of process or if I should handle things differently (e.g., forking to my personal repo and contributing like an open source collaborator). This seemed like it was a straightforward issue (which I opened). I figured I'd just jump into the PR instead of going through any discussion on the issue itself, but I'd obviously do that for a typical "bigger" issue.

**Review by jsign — APPROVED** [review]
Excellent, LGTM.

Yep, this flow is fine, [you only have to sign commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)!

**Comment by dtbuchholz** [comment]
Had some trouble with getting `make lint` to work properly as a pre-push check, in case there's a different formatting tool I should use. it looks like there may be a formatting fix I need to make (based on the diff)?

**Comment by jsign** [comment]
> Excellent, LGTM.
> 
> Yep, this flow is fine, [you only have to sign commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)!

@dtbuchholz , reg this you can configure your keys as described in the link, and then do something like the following in your local branch:
- `git reset HEAD^` (so you remove your last commit)
- `git add .` and `git commit -s -S -m 'your commit message again'`
- `git push --force`
-

**Comment by joewagner** [comment]
@dtbuchholz any reason not to merge this?

**Comment by dtbuchholz** [comment]
@joewagner nope, merging 👍.

**Pull request merged**
